# pull official base image
FROM python:3.10-bullseye

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
RUN pip install pipenv 
# RUN pipenv shell # Create file Pipfile and Pipfile.lock
COPY ./Pipfile  .
COPY ./Pipfile.lock .

RUN pipenv requirements > requirements.txt 
RUN pip install -r ./requirements.txt
# copy project
COPY . .

CMD ["python3", "manage.py", "runserver"]
